Fix default class
net375/theater-schedule-mobile pull request #15
Opened 2019-02-12 16:19 UTC by OlehSihunov

## Description (Include context, screenshots, ticket links etc.)

## PR Submission Reminders:
- Include a jira ticket with number and description*
- Please keep the PR as small as possible, reviewer should be able to review in less than 15 minutes
- Check if your PR havs no breaking changes

2019-02-12 16:57 UTC, andriy-mudrak reviewed
row 10 Please change name from InitialScreen to LanguageScreen
row 12 this.props.deviceID==undefined. The code will not be executed. You can use console.log( this.props.deviceID) for debugging 
row 22  Doesn see ./images/images.png in Repository
row 26. Change from SetLang("en") to this.SetLang("en")
Please delete initialScreen  file. It is superfluous

2019-02-12 17:19 UTC, andriy-mudrak commented on Navigation/Navigator.js
> +    initialcreen: { screen: LanguageScreen }
What is `initialcreen`?

2019-02-12 17:24 UTC, andriy-mudrak commented on Screens/LanguageScreen.js
> +        <TouchableOpacity onPress={()=>this.SetLang("ua")} style={styles.myButton}>
We don`t have "ua" language. Change this to "uk".

2019-02-13 22:08 UTC, taras-tymchuk requested changes
Don't delete "baseURL.js.example". There are URL templates to the local and remote servers, so everyone can use it.
Make a copy of this file and rename it to "baseURL.js". There you can make your changes (because "baseURL.js" is in .gitignore).

2019-02-14 08:50 UTC, vtorkalo approved these changes

2019-02-14 08:50 UTC, merged